<?php
/* This file is Copyright AltoLabs 2016. */
if (!$block->getShowVisitorScript()) { return; }
$fbId = $block->getFacebookId(true);
if (empty($fbId)) { return; }
$product = $block->getProductFromSession();
?>
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script','//connect.facebook.net/en_US/fbevents.js');
fbq('init', '<?php echo $fbId; ?>');
fbq('track', 'PageView');
<?php if ($product && $product->getId()) :
    // Note - Pierre: $total and $currency below are undefined, same in the M1 module - should this be the product price added to cart? ?>
    fbq('track', 'AddToCart', {
      value: '<?php echo $total; ?>',
      currency: '<?php echo $currency; ?>',
      content_type: 'product',
      content_ids: [<?php echo json_encode($block->getSnappicProductId($product)) ?>]],
    });
<?php endif; ?>
</script>
<noscript>
  <img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=<?php echo $fbId; ?>&ev=PageView&noscript=1" />
</noscript>
